const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key = 'folio-prototype-v1';
const states = ['Idea','Candidate','Decided','Superseded','Rejected'];
const seed = {
  goal:'Create a place for people to learn together.',
  subtitle:'Explore what a neighbourhood learning space could become.',
  constraints:['Start small: a six-week pilot','Use an existing neighbourhood venue','Keep participation free'],
  branch:'main', view:'map', selected:null, action:'Proposed',
  branches:[{id:'main',name:'Small, shared beginnings',note:'Test a weekly gathering before committing to a permanent space.',state:'Active',parent:null},{id:'digital',name:'An online commons',note:'Explore a digital space that neighbours can join from anywhere.',state:'Exploring',parent:'main'},{id:'permanent',name:'A permanent home',note:'Keep the long-term vision, with a larger commitment and more unknowns.',state:'Parked',parent:'main'}],
  objects:[
    {id:'E01',type:'evidence',title:'People want a reason to gather.',body:'In this fictional interview set, neighbours describe wanting informal ways to meet and learn with others.',note:'Interview notes · 3 excerpts',state:'Candidate',branch:'main',links:['S01'],quote:'“I would go if I could just turn up, learn something and meet someone from around here.”',origin:'Curated by you · illustrative evidence'},
    {id:'A01',type:'assumption',title:'A shared place builds belonging.',body:'We assume meeting in person will create stronger local connections than an online-only format. This has not been tested.',note:'Needs validation',state:'Idea',branch:'main',links:['Q01'],origin:'Added by you'},
    {id:'C01',type:'claim',title:'Start with a weekly learning circle.',body:'A recurring, low-commitment gathering could test interest before investing in a permanent space.',note:'1 supporting source · 1 caveat',state:'Candidate',branch:'main',links:['E01','E02','A01'],origin:'Model suggestion · illustrative synthesis'},
    {id:'Q01',type:'question',title:'Who is still missing?',body:'The interview sample excludes shift workers and people with caring responsibilities. Test whether the format works for them.',note:'Open question',state:'Idea',branch:'main',links:['E02'],origin:'Added by you'},
    {id:'D01',type:'decision',title:'Try a six-week pilot.',body:'Run one gathering a week at an existing venue. Revisit the format after six sessions, using attendance and participant feedback.',note:'Proposed direction',state:'Candidate',branch:'main',links:['C01','Q01'],origin:'Proposed by you'},
    {id:'O01',type:'artifact',title:'The pilot brief',body:'A working brief assembled from the goal, evidence, current decisions and unresolved questions.',note:'Living document',state:'Idea',branch:'main',links:['D01','C01'],origin:'Composed from workspace objects'},
    {id:'E02',type:'evidence',title:'Evenings do not work for everyone.',body:'A participant with caring responsibilities cannot commit to a fixed evening. The pilot could unintentionally exclude them.',note:'Interview notes · excerpt 4',state:'Candidate',branch:'main',links:['S02'],quote:'“A regular evening sounds nice, but I cannot promise I will be free every week.”',origin:'Curated by you · contradictory evidence'},
    {id:'S01',type:'source',title:'Neighbourhood conversations',body:'Fictional source document\n\nInterview 01: “I would go if I could just turn up, learn something and meet someone from around here.”\n\nInterview 02: “I have things I could teach. I just do not know where to start.”\n\nInterview 03: “Something regular, nearby and informal would be good.”',note:'Illustrative interview notes · page 1',state:'Candidate',branch:'main',links:[],origin:'Demo author · 15 September 2026'},
    {id:'S02',type:'source',title:'A different perspective',body:'Fictional source document\n\nInterview 04: “A regular evening sounds nice, but I cannot promise I will be free every week.”\n\nContext: a neighbour with caring responsibilities, commenting on an evening gathering.\n\nLimit: one account; it does not establish how widespread this constraint is.',note:'Illustrative interview notes · page 2',state:'Candidate',branch:'main',links:[],origin:'Demo author · 15 September 2026'},
    {id:'D02',type:'decision',title:'Keep participation free.',body:'Remove cost as a participation barrier during the pilot. Venue availability and volunteer capacity remain constraints.',note:'Constraint agreed',state:'Decided',branch:'main',links:[],origin:'Decided by you'},
    {id:'D03',type:'decision',title:'Build the online community first.',body:'Set aside as the primary direction because the current goal prioritises local, in-person connections. Preserved for future exploration.',note:'Alternative preserved',state:'Rejected',branch:'main',links:['A01'],origin:'Reviewed by you'}
  ],
  history:[{id:'D02',text:'Candidate → Decided',reason:'Remove cost as a barrier during the pilot.',time:'Initial example'},{id:'D03',text:'Candidate → Rejected',reason:'Keep the focus on in-person connection.',time:'Initial example'}]
};
let state;try{const stored=JSON.parse(localStorage.getItem(key));state=stored?.objects?.length&&stored?.branches?.length?stored:structuredClone(seed)}catch{state=structuredClone(seed)}
// Branches hold independent snapshots. Stable logical IDs allow the same object to appear in each view.
for(const branch of state.branches.filter(b=>b.id!=='main')) if(!state.objects.some(o=>o.branch===branch.id)){
  const copies=seed.objects.map(o=>({...structuredClone(o),branch:branch.id}));
  if(branch.id==='digital'){copies.find(o=>o.id==='C01').title='Start with an online commons.';copies.find(o=>o.id==='C01').body='Explore a digital gathering as an alternative. Access and sustained participation need testing.';copies.find(o=>o.id==='D01').title='Test one online gathering.';copies.find(o=>o.id==='D01').body='Invite neighbours to one online learning session before choosing a platform.';}
  if(branch.id==='permanent'){copies.find(o=>o.id==='C01').title='Create a permanent home.';copies.find(o=>o.id==='C01').body='Explore a dedicated neighbourhood space. A long-term venue requires funding and a sustainable operating model.';copies.find(o=>o.id==='D01').title='Investigate a long-term venue.';copies.find(o=>o.id==='D01').body='Identify venue costs and operating responsibilities before committing.';}
  state.objects.push(...copies);
}
const current = () => state.objects.filter(o=>o.branch===state.branch);
const obj = id => current().find(o=>o.id===id);
const badge = s => `<span class="state ${s.toLowerCase()}">${esc(s)}</span>`;
let toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4400)}
function save(){try{localStorage.setItem(key,JSON.stringify(state));$('#save-status').innerHTML='<i class="dot"></i> Saved on this device';}catch{$('#save-status').textContent='Session only · storage unavailable';}}
function setView(v){state.view=v;state.selected=null;state.showAskResult=false;render();}
function select(id){state.selected=id;state.showAskResult=false;render();const h=$('#inspector h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}if(innerWidth<=850)$('#inspector').scrollIntoView({block:'start'});}
function render(){
  $('#goal-title').textContent=state.goal;$('#goal-subtitle').textContent=state.subtitle;
  document.querySelectorAll('[data-view]').forEach(b=>{b.id='view-'+b.dataset.view;b.setAttribute('aria-controls','surface');b.setAttribute('aria-selected',b.dataset.view===state.view);b.tabIndex=b.dataset.view===state.view?0:-1;});
  $('#surface').setAttribute('role',state.view==='actions'?'region':'tabpanel');if(state.view!=='actions')$('#surface').setAttribute('aria-labelledby','view-'+state.view);else $('#surface').removeAttribute('aria-labelledby');
  $('#object-count').textContent=`${current().length} objects · ${state.branches.find(b=>b.id===state.branch)?.name||'Current branch'}`;
  $('#scope-label').textContent=state.selected?`@${state.selected} · ${obj(state.selected)?.title}`:'Whole workspace';
  $('#clear-selection').hidden=!state.selected;
  $('#action-peek-title').textContent=state.action==='Completed'?'Pilot brief prepared':state.action==='Declined'?'Pilot brief declined':'Prepare the pilot brief';
  $('.action-peek small').textContent=state.action==='Proposed'?'READY FOR YOUR REVIEW':state.action==='Completed'?'COMPLETED ON THIS DEVICE':'ACTION DECLINED';
  $('.action-peek span span').innerHTML=state.action==='Proposed'?'1 proposed action <b>→</b>':'Review action <b>→</b>';
  const views={map:renderMap,branches:renderBranches,evidence:renderEvidence,decisions:renderDecisions,document:renderDocument,actions:renderActions};
  $('#surface').innerHTML=(views[state.view]||renderMap)();
  const inspectorContent=window.renderModelProgress?.() || (state.showAskResult&&window.renderAskResult?renderAskResult():state.selected&&obj(state.selected)?renderInspector(obj(state.selected)):renderContext());
  $('#inspector').innerHTML=`<div class="inspector-scroll" tabindex="0" aria-label="Inspector content">${inspectorContent}</div>`;
  bindSurface();save();
  window.syncMapFullscreen?.();
  window.bindAskResults?.();
  window.bindAudioArtifacts?.();
}
function node(o){return `<button class="node ${o.type} ${state.selected===o.id?'selected':''}" data-object="${o.id}" aria-label="Open ${esc(o.title)}"><div class="node-header"><span class="type ${o.type}">${({evidence:'◈',assumption:'△',claim:'<span class="nous-artwork nous-symbol object-mark" aria-hidden="true"></span>',question:'?',decision:'◇',artifact:'▤'})[o.type]} ${o.type}</span></div><h3>${esc(o.title)}</h3><p>${esc(o.body.length>108?o.body.slice(0,105)+'…':o.body)}</p><div class="node-foot">${o.type==='decision'||o.type==='claim'?badge(o.state):`<span>${esc(o.note)}</span>`}<span>↗</span></div></button>`}
function renderMap(){return `<div class="map-viewport"><div class="map-content">${renderMapContent()}</div></div>`;}
function renderMapContent(){const selected=['E01','A01','C01','Q01','D01','O01'].map(obj).filter(Boolean);const extra=current().filter(o=>!selected.some(s=>s.id===o.id));return `<div class="map-wrap"><div class="surface-heading"><span>THE SHAPE OF THE WORK</span><label class="branch-switch">⑂ <select id="branch-select" aria-label="Active branch">${state.branches.map(b=>`<option value="${b.id}" ${b.id===state.branch?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label></div><div class="map-space"><svg class="connectors" viewBox="0 0 1000 420" preserveAspectRatio="none" aria-hidden="true"><path d="M265 95 C325 95 310 118 370 118"/><text x="297" y="91">supports</text><path class="dashed" d="M265 300 C335 300 300 150 370 150"/><text x="284" y="235">assumes</text><path d="M625 118 C680 118 675 94 730 94"/><text x="654" y="88">informs</text><path class="dashed" d="M500 280 L500 200"/><text x="512" y="244">challenges</text><path d="M860 178 L860 250"/><text x="873" y="210">becomes</text></svg>${selected.map(node).join('')}</div><div class="map-legend"><span><i class="legend-line"></i> Grounded relationship</span><span><i class="legend-line dash"></i> Assumption or open question</span><span>Select any object to inspect its context ↗</span></div></div>${extra.length?`<div class="extra-list">${extra.map(o=>`<button class="extra-object" data-object="${o.id}"><span class="type ${o.type}">${o.type}</span><strong>${esc(o.title)}</strong><p>${esc(o.note||'Added to this branch')}</p>${badge(o.state)}</button>`).join('')}</div>`:''}`;}
function renderContext(){const thoughts=current().filter(o=>['claim','assumption'].includes(o.type)&&!['Rejected','Superseded'].includes(o.state));const questions=current().filter(o=>o.type==='question'&&!['Rejected','Superseded','Decided'].includes(o.state));const items=list=>list.length?list.slice(0,5).map(o=>`<li><button data-object="${esc(o.id)}">${esc(o.title)} ↗</button></li>`).join(''):'<li>Nothing recorded yet.</li>';return `<div class="inspector-eyebrow">SHARED CONTEXT <button data-context aria-label="Edit shared context">↗</button></div><h2 class="context-title">A place to begin.</h2><p class="context-lead">The current branch’s thinking, boundaries and open questions.</p><div class="context-group"><h3>CURRENT THINKING</h3><ul>${items(thoughts)}</ul></div><div class="context-group"><h3>BOUNDARIES</h3><ul>${state.constraints.map(c=>`<li>${esc(c)}</li>`).join('')}</ul></div><div class="context-group"><h3>STILL OPEN · ${questions.length}</h3><ul>${items(questions)}</ul>${questions.length>5?'<p class="source-note">More questions are available in Map and Document.</p>':''}</div><div class="context-footer">Follow each object to its source. Seed evidence is fictional; AI drafts need review.</div>`}

function renderInspector(o){return `<div class="inspector-eyebrow">OBJECT INSPECTOR <button data-close aria-label="Close object inspector">×</button></div><div class="node-header"><span class="type ${o.type}">${o.type}</span></div><h2 class="inspector-title">${esc(o.title)}</h2>${o.quote?`<blockquote class="quote">${esc(o.quote)}</blockquote>`:''}<p class="inspector-body" style="white-space:pre-line">${esc(o.body)}</p><div class="source-note"><strong>${esc(o.origin)}</strong><br>${esc(o.note)}<br>Branch: ${esc(state.branches.find(b=>b.id===o.branch)?.name)}</div>${o.type==='decision'?`<div class="inspector-label">DECISION STATE</div><select id="decision-state" class="inspector-state" aria-label="Decision state">${states.map(s=>`<option ${s===o.state?'selected':''}>${s}</option>`).join('')}</select>`:`<div class="inspector-label">CURRENT STATE</div>${badge(o.state)}`}${o.audioId?`<div class="audio-artifact" data-audio-id="${esc(o.audioId)}"><p>AI-generated audio</p><audio controls preload="none" aria-label="Saved audio"></audio><a download="nous-audio.mp3" hidden>Download audio</a><p role="status"></p></div>`:''}${o.links.length?`<div class="inspector-label">${o.type==='evidence'?'ORIGINAL MATERIAL':'CONNECTED OBJECTS'}</div><div class="object-links">${o.links.map(id=>obj(id)).filter(Boolean).map(x=>`<button data-object="${x.id}"><span class="type ${x.type}">${x.type}</span><br>${esc(x.title)} ↗</button>`).join('')}</div>`:''}<div class="inspector-controls"><button data-edit="${o.id}">Edit object</button><button data-branch="${o.id}">⑂ Branch</button>${o.type==='assumption'||o.type==='claim'?`<button data-challenge="${o.id}">Challenge</button>`:''}</div>${state.history.filter(h=>h.id===o.id&&(!h.branch||h.branch===state.branch)).length?`<div class="inspector-label">DECISION HISTORY</div>${state.history.filter(h=>h.id===o.id&&(!h.branch||h.branch===state.branch)).slice(-4).reverse().map(h=>`<div class="change-entry"><strong>${esc(h.text)}</strong>${esc(h.reason)}<br>${esc(h.time)}</div>`).join('')}`:''}`}
function renderBranches(){return `<div class="view-page"><div class="section-top"><div><div class="page-kicker">EXPLORATION, WITHOUT ERASURE</div><h2>Let the work take another path.</h2></div><button class="subtle-button" data-new-branch>＋ Create a branch</button></div><p class="page-intro">Each direction keeps its own objects and decisions. The original remains intact.</p><div class="branch-root"><strong>${esc(state.goal)}</strong>Shared goal & context</div><div class="branch-grid">${state.branches.map((b,i)=>`<article class="branch-card ${state.branch===b.id?'active':''}"><div class="node-header"><span class="type">PATH ${String(i+1).padStart(2,'0')}</span><span class="state ${b.state==='Active'?'decided':'candidate'}">${esc(b.state)}</span></div><h3>${esc(b.name)}</h3><p>${esc(b.note)}</p><div class="branch-meta"><span>${state.objects.filter(o=>o.branch===b.id).length} objects preserved</span><span>${b.parent?'⑂ Forked from '+esc(state.branches.find(x=>x.id===b.parent)?.name||'main'):'Original direction'}</span></div><div class="branch-tools"><button data-open-branch="${b.id}">${state.branch===b.id?'Continue exploring':'Open this branch'} ↗</button>${b.id!=='main'?`<button data-archive-branch="${b.id}">${b.state==='Archived'?'Restore':'Archive'}</button>`:''}</div></article>`).join('')}</div><p class="branch-note">An alternative is a branch of the work, not a replacement for it.</p></div>`}
function renderEvidence(){return `<div class="view-page"><div class="page-kicker">EVIDENCE & PROVENANCE</div><h2>Follow a thought back to its source.</h2><p class="page-intro">Supporting material, contrary evidence and the limits of what we know.</p><div class="lineage"><span>CLAIM</span>←<span>EVIDENCE</span>←<span>ORIGINAL SOURCE</span></div><div class="evidence-list">${current().filter(o=>o.type==='evidence').map((o,i)=>`<button class="evidence-card ${i?'contradiction':''}" data-object="${o.id}"><div class="node-header"><span class="type evidence">${i?'△ COMPLICATES THE CLAIM':'◈ SUPPORTS THE CLAIM'}</span></div><h3>${esc(o.title)}</h3>${o.quote?`<blockquote>${esc(o.quote)}</blockquote>`:`<p>${esc(o.body)}</p>`}<footer><span>${esc(o.note)}</span><span>Inspect source ↗</span></footer></button>`).join('')}</div><div class="context-group"><h3>LIMITS OF THIS EVIDENCE</h3><p class="page-intro">Four fictional conversations illustrate the interaction. They do not establish demand, represent a neighbourhood or validate the proposed format.</p></div></div>`}
function renderDecisions(){return `<div class="view-page"><div class="page-kicker">A RECORD OF INTENT</div><h2>Make the current direction unmistakable.</h2><p class="page-intro">Ideas can change. The reason for a decision stays attached to the work.</p><div class="state-strip">${states.map(s=>`<span class="${s.toLowerCase()}">${s}</span>`).join('<span style="background:none;padding:8px 0">→</span>')}</div>${current().filter(o=>o.type==='decision').map(o=>`<div class="decision-row"><div>${badge(o.state)}</div><button data-object="${o.id}"><h3>${esc(o.title)}</h3><p>${esc(o.body)}</p></button><div class="row-meta"><span>${esc(o.id)} · ${esc(o.origin)}</span>${o.links.length} connected objects<br><button data-object="${o.id}">Review decision ↗</button></div></div>`).join('')}</div>`}
function renderDocument(){const focus=current().filter(o=>['claim','decision','question','artifact'].includes(o.type)).sort((a,b)=>['claim','decision','question','artifact'].indexOf(a.type)-['claim','decision','question','artifact'].indexOf(b.type));return `<div class="view-page"><div class="section-top"><div class="page-kicker">SAME OBJECTS · ANOTHER WAY TO THINK</div><button class="subtle-button" id="download-brief">Download brief ↗</button></div><article class="document-paper"><div class="doc-live"><span>THE PILOT BRIEF</span><span>↻ CONNECTED TO ${focus.length} OBJECTS</span></div><h2>${esc(state.goal)}</h2><p class="doc-deck">${esc(state.subtitle)}</p>${focus.map(o=>`<section class="doc-section"><div class="node-header"><span class="type ${o.type}">${o.type}</span>${badge(o.state)}</div><button data-object="${o.id}" style="text-align:left;padding:0"><h3>${esc(o.title)}</h3></button><p>${esc(o.body)}</p><button class="ref" data-object="${o.id}">↗ ${o.id} · Inspect ${o.links.length} connections</button></section>`).join('')}<p class="source-note">Living view of this branch. Fictional example; not validated research.</p></article></div>`}
function renderActions(){return `<div class="view-page"><div class="page-kicker">INTENT BECOMES ACTION</div><h2>See the change before it happens.</h2><p class="page-intro">A bounded proposal, with the source, scope and outcome visible.</p><article class="action-card"><div class="node-header"><span class="type artifact">▤ LOCAL ARTIFACT</span>${badge(state.action)}</div><h3>Prepare the pilot brief</h3><div class="action-grid"><div><small>INPUTS</small><p>Shared goal, current branch, claims,<br>decisions and unresolved questions.</p></div><div><small>WHAT WILL CHANGE</small><p>Update the pilot brief object.<br>Download one Markdown file.</p></div><div><small>DESTINATION & IMPACT</small><p>This device only. No messages sent.<br>This action uses no external service.</p></div><div><small>CONTROL</small><p>Runs only after your approval.<br>Existing workspace objects are preserved.</p></div></div><div class="action-preview"><span class="type artifact">PREVIEW</span><br><strong>${esc(state.goal)}</strong><br>${esc(obj('D01')?.title)} · ${esc(obj('D01')?.state)}<br>${current().filter(o=>o.type==='question').length} unresolved question(s) included, with object references.</div><div class="action-footer"><button id="approve-action" class="primary" ${state.action==='Completed'?'disabled':''}>${state.action==='Completed'?'✓ Brief prepared':'Approve & download brief'}</button><button id="reject-action" ${state.action!=='Proposed'?'disabled':''}>Decline</button><span>${state.action==='Declined'?'Declined. Nothing was changed.':state.action==='Completed'?'Completed locally. No external action.':'Awaiting your approval'}</span>${state.action!=='Proposed'?'<button id="reopen-action">Propose again</button>':''}</div></article></div>`}
function bindSurface(){
  document.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>select(b.dataset.object));
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{const id=state.selected;state.selected=null;render();document.querySelector('[data-object="'+id+'"]')?.focus({preventScroll:true});});
  document.querySelectorAll('[data-context]').forEach(b=>b.onclick=editContext);
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editObject(b.dataset.edit));
  document.querySelectorAll('[data-branch]').forEach(b=>b.onclick=()=>branchDialog(b.dataset.branch));
  document.querySelectorAll('[data-challenge]').forEach(b=>b.onclick=()=>challenge(b.dataset.challenge));
  document.querySelectorAll('[data-new-branch]').forEach(b=>b.onclick=()=>branchDialog());
  document.querySelectorAll('[data-open-branch]').forEach(b=>b.onclick=()=>{state.branch=b.dataset.openBranch;setView('map');toast('Branch opened. Changes stay within this direction.')});
  document.querySelectorAll('[data-archive-branch]').forEach(b=>b.onclick=()=>{const branch=state.branches.find(x=>x.id===b.dataset.archiveBranch);branch.state=branch.state==='Archived'?'Exploring':'Archived';render();toast(`Branch ${branch.state.toLowerCase()}. All objects are preserved.`)});
  if($('#branch-select'))$('#branch-select').onchange=e=>{state.branch=e.target.value;state.selected=null;render()};
  if($('#decision-state'))$('#decision-state').onchange=e=>decisionDialog(state.selected,e.target.value);
  if($('#download-brief'))$('#download-brief').onclick=()=>downloadBrief();
  if($('#approve-action'))$('#approve-action').onclick=()=>{downloadBrief();state.action='Completed';const artifact=obj('O01');if(artifact){artifact.state='Decided';artifact.note='Brief prepared locally'}render();toast('Brief prepared and downloaded. No external action was taken.')};
  if($('#reject-action'))$('#reject-action').onclick=()=>{state.action='Declined';render();toast('Action declined. Workspace content is unchanged.')};
  if($('#reopen-action'))$('#reopen-action').onclick=()=>{state.action='Proposed';render()};
}
function modal(html,onSubmit){
  state.showAskResult=false;
  const d=$('#dialog');d.innerHTML=html;const heading=d.querySelector('h2');if(heading){heading.id='dialog-title';d.setAttribute('aria-labelledby','dialog-title');}d.showModal();
  const complete=saved=>d.dispatchEvent(new CustomEvent('workspaceformcomplete',{detail:{saved}}));
  d.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{complete(false);d.close();render()});
  const f=d.querySelector('form');if(f)f.onsubmit=e=>{e.preventDefault();onSubmit(new FormData(f));complete(true);d.close();render()};
  d.oncancel=()=>{complete(false);requestAnimationFrame(render)};
}
const modalActions=(label='Save changes')=>`<div class="dialog-actions"><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">${label}</button></div>`;
function editContext(){modal(`<h2>Context that stays with the work.</h2><p>The goal and constraints are shared by all branches.</p><form><label>Goal<input name="goal" value="${esc(state.goal)}" required maxlength="140"></label><label>Intent<input name="subtitle" value="${esc(state.subtitle)}" required maxlength="200"></label><label>Constraints · one per line<textarea name="constraints" required>${esc(state.constraints.join('\n'))}</textarea></label>${modalActions()}</form>`,f=>{state.goal=f.get('goal').trim();state.subtitle=f.get('subtitle').trim();state.constraints=f.get('constraints').split('\n').map(x=>x.trim()).filter(Boolean);toast('Shared context updated across all views and branches.')})}
function editObject(id){const o=obj(id);modal(`<h2>Edit the ${o.type}.</h2><p>${esc(o.id)} retains its identity and connections in every view.</p><form><label>Title<input name="title" value="${esc(o.title)}" required maxlength="150"></label><label>Content<textarea name="body" required>${esc(o.body)}</textarea></label>${modalActions()}</form>`,f=>{o.title=f.get('title').trim();o.body=f.get('body').trim();o.origin='Edited by you';toast('Object updated. Connected views now use this version.')})}
function addObject(){modal(`<h2>Give an idea a place.</h2><p>Add a typed object to the current branch.</p><form><label>Type<select name="type">${['claim','question','assumption','evidence','decision','artifact','source'].map(t=>`<option>${t}</option>`).join('')}</select></label><label>Title<input name="title" required maxlength="150" placeholder="What should we keep track of?"></label><label>Content<textarea name="body" required placeholder="Add the detail that should persist."></textarea></label>${modalActions('Create object')}</form>`,f=>createObject(f.get('type'),f.get('title').trim(),f.get('body').trim()))}
function createObject(type,title,body,links=[]){const id=type[0].toUpperCase()+crypto.randomUUID().slice(0,8).toUpperCase();state.objects.push({id,type,title,body,links,branch:state.branch,state:'Idea',note:'Added to this branch',origin:'Created by you'});state.selected=id;state.view='map';toast(`${type[0].toUpperCase()+type.slice(1)} created as @${id}.`);return id;}
function branchDialog(from){modal(`<h2>Keep both possibilities.</h2><p>Create an independent copy of this branch${from?' from @'+esc(from):''}, including objects and their evidence links.</p><form><label>Branch name<input name="name" required maxlength="60" placeholder="What if we tried…"></label><label>What will this branch explore?<textarea name="note" required placeholder="A different direction, question or constraint."></textarea></label>${modalActions('Create branch')}</form>`,f=>{const id='b'+Date.now().toString(36);state.branches.push({id,name:f.get('name').trim(),note:f.get('note').trim(),parent:state.branch,state:'Exploring'});state.objects.push(...current().map(o=>({...structuredClone(o),branch:id})));state.history.push(...state.history.filter(h=>h.branch===state.branch||(!h.branch&&state.branch==='main')).map(h=>({...h,branch:id})));state.branch=id;state.selected=null;state.view='branches';toast('New branch created with independent copies. The original is preserved.')})}
function decisionDialog(id,next){const o=obj(id);const prev=o.state;modal(`<h2>Make the decision explicit.</h2><p>${esc(o.title)}<br>${esc(prev)} → ${esc(next)}</p><form><label>Reason for the change<textarea name="reason" required placeholder="What changed, and why?"></textarea></label>${modalActions('Record decision')}</form>`,f=>{o.state=next;o.origin='Reviewed by you';o.note='Decision recorded';state.history.push({id,branch:state.branch,text:`${prev} → ${next}`,reason:f.get('reason').trim(),time:new Date().toLocaleString()});toast('Decision recorded, with its rationale. Every view is updated.')})}
function challenge(id){const o=obj(id)||obj('A01');const newId=createObject('question',`What would challenge: ${o.title}`,`Explore a counterexample to @${o.id}. What evidence would make us revise this ${o.type}?\n\nLocal demo: this is a research prompt, not a model-generated finding.`,[o.id]);o.links.push(newId);render();toast('A linked challenge was created. No new evidence has been invented.')}
function briefText(){return `# ${state.goal}\n\n${state.subtitle}\n\nBranch: ${state.branches.find(b=>b.id===state.branch).name}\n\nSeed sources are fictional. AI drafts are labelled with their provider and require review.\n\n## Constraints\n${state.constraints.map(c=>'- '+c).join('\n')}\n\n${current().filter(o=>['claim','decision','question','evidence','artifact'].includes(o.type)&&o.id!=='O01').map(o=>`## ${o.type.toUpperCase()} ${o.id}: ${o.title}\n\nState: ${o.state}\n\n${o.body}\n\nConnections: ${o.links.join(', ')||'None'}\n\nProvenance: ${o.origin}\n`).join('\n')}\n## Decision history\n${state.history.filter(h=>h.branch===state.branch||(!h.branch&&state.branch==='main')).map(h=>`${h.id}: ${h.text}. ${h.reason}`).join('\n')}`;}
function download(name,text,type){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function downloadBrief(){download('Nous-pilot-brief.md',briefText(),'text/markdown');toast('The current branch brief was downloaded.')}
function help(){modal(`<h2>Work has a shape.</h2><p>Nous is an interaction prototype. Objects and branches are stored in this browser. Choose ChatGPT or Claude beside Ask for model answers and linked drafts. Local commands work without a model. Connections shows API setup status. External actions still require review.</p><div class="help-row"><strong>(1) Inspect</strong><span>Select any object. Follow its links to evidence and the original source.</span></div><div class="help-row"><strong>(2) Explore</strong><span>Create a branch, edit its objects, then return to the original.</span></div><div class="help-row"><strong>(3) Decide</strong><span>Select a decision, change its state and record why.</span></div><div class="help-row"><strong>(4) Direct</strong><span>Try “Compare the alternatives”, “Draft the brief”, or “Create a question: Which venue is available?”</span></div><div class="help-row"><strong>(5) Keep</strong><span>Download the current brief.</span></div><div class="dialog-actions"><button data-cancel class="primary">Start exploring</button></div>`)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{$('#command').value=b.dataset.command;$('#command').focus()});
$('#command-form').onsubmit=e=>{e.preventDefault();window.submitAsk?.()};
$('#edit-context').onclick=editContext;$('#add-object').onclick=addObject;$('#review-actions').onclick=()=>setView('actions');$('#help').onclick=help;
$('#clear-selection').onclick=()=>{state.selected=null;render()};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#command').focus()}});
render();

// Roving tab focus follows the visible workspace views.
document.querySelector('.views').addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[data-view]')];let i=tabs.indexOf(e.target);if(i<0||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[i].click();tabs[i].focus();});
